---
name: RPM Build
on: 
  workflow_dispatch:
  push:
    paths:
      - hf-provider/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8", "9", "10"]
        include:
          - python_pkg: python39
            version: 8
          - python_pkg: python39
            version: 9
          - python_pkg: python3
            version: 10
    container:
      image: rockylinux/rockylinux:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2

    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
        fi

    - name: Check if a valid SemVer tag
      if: steps.check-tag.outputs.match == 'true'
      run: |
        # Extract the version part (e.g., 1.2.3)
        VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')

    - name: Run on any other tag
      if: steps.check-tag.outputs.match != 'true'
      run: VERSION='1.0.0'

    - name: install required rpm packages
      run: |
           dnf install -y ${{ matrix.python_pkg }} rpm-build nodejs
           alternatives --set python3 /usr/bin/python3.9 || true

    - name: Add a directory to the PATH
      run: echo "/usr/bin" >> $GITHUB_PATH

    - name: build clis
      run: |
           cd hf-provider
           curl -LsSf https://astral.sh/uv/install.sh | sh
           source $HOME/.local/bin/env
           uv venv
           source .venv/bin/activate
           uv pip install -r pyproject.toml
           uv pip install pyinstaller
           PYTHONPATH=src pyinstaller --onefile src/gce_provider/__main__.py --name hf-gce --paths .venv/lib/python3.9/site-packages
           PYTHONPATH=src pyinstaller --onefile src/gke_provider/__main__.py --name hf-gke --paths .venv/lib/python3.9/site-packages

    - name: run gce rpmbuild
      id: gce-rpm
      run: rpmbuild -bb hf-provider/resources/hf-gcpgce-provider.spec | grep Wrote |awk '{print "gce_rpm_path="$2}' >> $GITHUB_OUTPUT

    - name: Upload gce artifact
      uses: actions/upload-artifact@v4
      with:
        name: hf-gcpgce-provider-$VERSION-${{ github.run_number }}.el${{ matrix.version }}.x86_64.rpm
        path: "${{ steps.gce-rpm.outputs.gce_rpm_path }}"
        compression-level: 0

    - name: run gke rpmbuild
      id: gke-rpm
      run: rpmbuild -bb hf-provider/resources/hf-gcpgke-provider.spec | grep Wrote |awk '{print "gke_rpm_path="$2}' >> $GITHUB_OUTPUT

    - name: Upload gke artifact
      uses: actions/upload-artifact@v4
      with:
        name: hf-gcpgke-provider-$VERSION-${{ github.run_number }}.el${{ matrix.version }}.x86_64.rpm
        path: "${{ steps.gke-rpm.outputs.gke_rpm_path }}"
        compression-level: 0

